before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - node -v
  - which node
  - npm -v
  - which npm
  - npm install

test:
  script:
    - npm test

lint:
  script:
    - npm run lint
